# Generated by Django 6.1 on 2026-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideparticipant',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
