# Generated by Django 6.1 on 2026-08-21 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rideparticipant_is_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='route_distance_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_duration_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_polyline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='RidePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('heading', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pages.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ride', 'user')},
            },
        ),
    ]
