# Generated by Django 6.1 on 2026-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_phone_public',
            field=models.BooleanField(default=False),
        ),
    ]
