# Generated by Django 6.1 on 2026-08-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile_is_email_public_profile_is_phone_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='riding_style',
            field=models.CharField(blank=True, choices=[('ADVENTURE', 'Adventure'), ('SPORT', 'Sport'), ('TOURING', 'Touring'), ('CRUISE', 'Cruise'), ('COMMUTE', 'Commute'), ('ALL', 'All Styles')], default='', max_length=20),
        ),
    ]
